name: SunOfSkyDIMENSION
main: net.joueuranonyme.sunofsky.dimension.Main
version: "1.0"
api-version: 1.18

softdepend: [PlaceholderAPI]

commands: 
  dimension:
    usage: "§cUsage : /dimension"

permissions: {}
  # Permissions